version: "3.8"

services:
  web:
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pandu@2k3
      POSTGRES_DB: echodb
    ports:
      - "5433:5432"
