services:
  web:
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      - USE_TTS=false  # Set to true for local TTS
    restart: always

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pandu@2k3
      POSTGRES_DB: echodb
    ports:
      - "5432:5432"
