version: "3.9"
services:
  web:
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      - USE_TTS=false
    restart: always

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
